/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.SachDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Sach;
/**
 *
 * @author Ther
 */
public class DanhSachSanPham extends javax.swing.JFrame {
    
    public static DanhSachSanPham Instance;
    
    Vector data = new Vector();
    Vector<String> header = new Vector();
    boolean addNew = false;
    boolean changed = false;
    
    /**
     * Creates new form DanhSachSanPham
     */
    public DanhSachSanPham() {
        initComponents();
        loadDanhSachSach();
        Instance = this;
    }
    public void loadDanhSachSach() {

        header.add("Ma Sach");
        header.add("Ten Sach");
        header.add("Gia Ban");
        header.add("Mo Ta");
        header.add("Ngay Cap Nhat");
        header.add("Anh Bia");
        header.add("So Luong Ton");
        header.add("Ma Chu De");
        header.add("Ma NXB");
        header.add("Moi");

        DefaultTableModel model;
        model = (DefaultTableModel) this.tbListSach.getModel();

        loadData();
        model.setDataVector(data, header); 

    }
    
    public void loadMaNXB_Search() {

        cbbMaNXB_Search.addItem("Khong");
        for (Object type : SachDAO.getNXBTypes()) {
            String typeName = String.valueOf(type);
            // Loại bỏ dấu [ và ] nếu có
            typeName = typeName.replace("[", "").replace("]", "");
            cbbMaNXB_Search.addItem(typeName);
        }
    }
    
    public void loadMaTheLoaiSearch() {
        cbbMaChuDe_Search.addItem("Khong");
        for (Object type : SachDAO.getBookTypes()) {
            String typeName = String.valueOf(type);
            // Loại bỏ dấu [ và ] nếu có
            typeName = typeName.replace("[", "").replace("]", "");
            cbbMaChuDe_Search.addItem(typeName);
        }

    }

    
    public void loadMaTheLoai_Search() {
        cbbMaChuDe.addItem("Khong");
        for (Object type : SachDAO.getBookTypes()) {
            String typeName = String.valueOf(type);
            // Loại bỏ dấu [ và ] nếu có
            typeName = typeName.replace("[", "").replace("]", "");
            cbbMaChuDe.addItem(typeName);
        }
    }
    public void loadData() {

        ArrayList<Sach> lstAllSach = SachDAO.hienThiDanhSachSach();

        for (Sach sach : lstAllSach) {

            Vector<Object> vec = new Vector<>();
            
            vec.add(sach.getMasach());
            vec.add(sach.getTensach());
            vec.add(sach.getGiaban());
            vec.add(sach.getMota());
            vec.add(sach.getNgaycapnhat());
            vec.add(sach.getMaanhbia());
            vec.add(sach.getSoluongton());
            vec.add(sach.getMachude());
            vec.add(sach.getManxb());
            vec.add(sach.getMoi());
            data.add(vec);
        }
        
        loadMaTheLoai_Search();
        loadMaNXB_Search();
        loadMaTheLoaiSearch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMaSach_Search = new javax.swing.JTextField();
        txtTenSach_Search = new javax.swing.JTextField();
        priceMin = new javax.swing.JTextField();
        priceMax = new javax.swing.JTextField();
        cbbMaTheLoai = new javax.swing.JComboBox<>();
        cbbMaNXB = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        titlePage = new javax.swing.JLabel();
        Middle = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtMaSach_Search_DSSP = new javax.swing.JTextField();
        txtTenSach_Search_DSSP = new javax.swing.JTextField();
        priceMin_DSSP = new javax.swing.JTextField();
        priceMax_DSSP = new javax.swing.JTextField();
        cbbMaChuDe_Search = new javax.swing.JComboBox<>();
        cbbMaNXB_Search = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        bntTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtTacGia_Search = new javax.swing.JTextField();
        Footer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        cbbMaChuDe = new javax.swing.JComboBox<>();
        txtMaNXB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListSach = new javax.swing.JTable();
        bntXacNhan = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 22), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("MÃ SÁCH:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("MÃ THỂ LOẠI:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("TÊN SÁCH:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("---");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("KHOẢNG GIÁ:");

        txtMaSach_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSach_SearchActionPerformed(evt);
            }
        });

        cbbMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaNXBActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("MÃ NXB:");

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setText("Tim Kiem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(priceMin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSach_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceMax, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSach_Search))
                    .addComponent(cbbMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMaSach_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(cbbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtTenSach_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(priceMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(priceMax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbbMaTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 153, 153));
        Header.setForeground(new java.awt.Color(0, 255, 255));

        titlePage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePage.setForeground(new java.awt.Color(255, 255, 255));
        titlePage.setText("DANH SÁCH SẢN PHẨM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlePage)
                .addGap(368, 368, 368))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titlePage)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Middle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 22), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("MÃ SÁCH:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("MÃ THỂ LOẠI:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("TÊN SÁCH:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("---");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("KHOẢNG GIÁ:");

        txtMaSach_Search_DSSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSach_Search_DSSPActionPerformed(evt);
            }
        });

        cbbMaNXB_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaNXB_SearchActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("MÃ NXB:");

        bntTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        bntTimKiem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bntTimKiem.setText("Tim Kiem");
        bntTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(0, 153, 0));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("TÁC GIẢ");

        javax.swing.GroupLayout MiddleLayout = new javax.swing.GroupLayout(Middle);
        Middle.setLayout(MiddleLayout);
        MiddleLayout.setHorizontalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(priceMin_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiddleLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSach_Search_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceMax_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbMaNXB_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMaChuDe_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSach_Search_DSSP))
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtTacGia_Search)
                        .addGap(1, 1, 1)))
                .addGap(74, 74, 74)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        MiddleLayout.setVerticalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaSach_Search_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(cbbMaNXB_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenSach_Search_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(priceMin_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(priceMax_DSSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(cbbMaChuDe_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtTacGia_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MiddleLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(bntTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("MÃ SÁCH:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("MÃ NXB:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("MÃ THỂ LOẠI:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("TÊN SÁCH:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("SỐ LƯỢNG:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ĐƠN GIÁ:");

        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });

        cbbMaChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaChuDeActionPerformed(evt);
            }
        });

        tbListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbListSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListSachMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbListSachMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbListSach);

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FooterLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FooterLayout.createSequentialGroup()
                                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                                        .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(FooterLayout.createSequentialGroup()
                                .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(352, 352, 352)))
                        .addGap(213, 213, 213))
                    .addGroup(FooterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbbMaChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bntXacNhan.setBackground(new java.awt.Color(153, 153, 0));
        bntXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntXacNhan.setText("Xác Nhận");
        bntXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Middle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(bntXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSach_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSach_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSach_SearchActionPerformed

    private void cbbMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMaNXBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        actionSearchMaSach();
//        actionSearchMaNXB();
//        actionSearchTypes();
//        actionSearchPriceAndNXB();
//        actionSearchNameBook();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbbMaNXB_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaNXB_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMaNXB_SearchActionPerformed

    private void bntTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTimKiemActionPerformed
        // TODO add your handling code here:

        actionSearchMaSach();
        actionSearchMaNXB();
        actionSearchTypes();
        actionSearchPriceAndNXB();
        actionSearchNameBook();
        actionSearchNameAuthor();
    }//GEN-LAST:event_bntTimKiemActionPerformed
    
    private void actionSearchNameAuthor() {
        String authorName = String.valueOf(this.txtTacGia_Search.getText());
        if (!authorName.isEmpty()) {
            data = new Vector();
            DefaultTableModel model;
            model = (DefaultTableModel) this.tbListSach.getModel();
            ArrayList<Sach> lstBookById = SachDAO.getBookByAuthor(authorName);
            if (!lstBookById.isEmpty()) {
                 for (Sach sach : lstBookById) {
                    Vector<Object> vec = new Vector<>();
                    vec.add(sach.getMasach());
                    vec.add(sach.getTensach());
                    vec.add(sach.getGiaban());
                    vec.add(sach.getMota());
                    vec.add(sach.getNgaycapnhat());
                    vec.add(sach.getMaanhbia());
                    vec.add(sach.getSoluongton());
                    vec.add(sach.getMachude());
                    vec.add(sach.getManxb());
                    vec.add(sach.getMoi());
                    data.add(vec);
                }
            }
            model.setDataVector(data, header); 
        }

    }
    
    private void actionSearchNameBook() {
        String bookName = String.valueOf(this.txtTenSach_Search_DSSP.getText());
        if (!bookName.isEmpty()) {
            data = new Vector();
            DefaultTableModel model;
            model = (DefaultTableModel) this.tbListSach.getModel();
            ArrayList<Sach> lstBookById = SachDAO.getBookByName(bookName);
            if (!lstBookById.isEmpty()) {
                 for (Sach sach : lstBookById) {
                    Vector<Object> vec = new Vector<>();
                    vec.add(sach.getMasach());
                    vec.add(sach.getTensach());
                    vec.add(sach.getGiaban());
                    vec.add(sach.getMota());
                    vec.add(sach.getNgaycapnhat());
                    vec.add(sach.getMaanhbia());
                    vec.add(sach.getSoluongton());
                    vec.add(sach.getMachude());
                    vec.add(sach.getManxb());
                    vec.add(sach.getMoi());
                    data.add(vec);
                }
            }
            model.setDataVector(data, header); 
        }

    }
    private void actionSearchMaNXB() {
        String maNXB = String.valueOf(cbbMaNXB_Search.getSelectedItem());
        if(maNXB != "Khong") {
            data = new Vector();
            DefaultTableModel model;
            model = (DefaultTableModel) this.tbListSach.getModel();
            ArrayList<Sach> lstBookById = SachDAO.getBookByNXB(maNXB);
            if (!lstBookById.isEmpty()) {
                 for (Sach sach : lstBookById) {
                    Vector<Object> vec = new Vector<>();
                    vec.add(sach.getMasach());
                    vec.add(sach.getTensach());
                    vec.add(sach.getGiaban());
                    vec.add(sach.getMota());
                    vec.add(sach.getNgaycapnhat());
                    vec.add(sach.getMaanhbia());
                    vec.add(sach.getSoluongton());
                    vec.add(sach.getMachude());
                    vec.add(sach.getManxb());
                    vec.add(sach.getMoi());
                     System.out.println(vec);
                    data.add(vec);
                }
            }
            model.setDataVector(data, header); 
        }
    }
     private void actionSearchPriceAndNXB() {
        String typesNXB = String.valueOf(cbbMaNXB_Search.getSelectedItem());
         System.out.println(typesNXB);
        if(typesNXB != "Khong") {
                double min = 0;
                double max = 0;
                if (!priceMax_DSSP.getText().isEmpty() && !priceMin_DSSP.getText().isEmpty()) {
                    if(priceMin_DSSP.getText().matches("-?\\d+") && priceMax_DSSP.getText().matches("-?\\d+") ) {
                        min = Integer.parseInt(priceMin_DSSP.getText());
                        max = Integer.parseInt(priceMax_DSSP.getText());
                        if(min < 0 || max <= 0) {
                            JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ", "Invalid", JOptionPane.OK_CANCEL_OPTION);
                        } else if (max <= min) {
                            JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ", "Invalid", JOptionPane.OK_CANCEL_OPTION);
                        }
                        else { // Truong hop nguoi dung nhap menh gia tien
                                data = new Vector();
                                DefaultTableModel model;
                                model = (DefaultTableModel) this.tbListSach.getModel();
                                ArrayList<Sach> lstBookById = SachDAO.getBookByPriceAndNXB(min, max, typesNXB);
                                if (!lstBookById.isEmpty()) {
                                     for (Sach sach : lstBookById) {
                                        Vector<Object> vec = new Vector<>();
                                        vec.add(sach.getMasach());
                                        vec.add(sach.getTensach());
                                        vec.add(sach.getGiaban());
                                        vec.add(sach.getMota());
                                        vec.add(sach.getNgaycapnhat());
                                        vec.add(sach.getMaanhbia());
                                        vec.add(sach.getSoluongton());
                                        vec.add(sach.getMachude());
                                        vec.add(sach.getManxb());
                                        vec.add(sach.getMoi());
                                        data.add(vec);
                                    }
                                }
                                model.setDataVector(data, header);
                        }
                    }else {
                         JOptionPane.showMessageDialog(this, "Giá tiền phải là số", "Error", JOptionPane.OK_CANCEL_OPTION);
                    }      
        }
        } else {
            actionSearchPrice();
        }
    }

     private void actionSearchPrice() {
        double min = 0;
        double max = 0;
        if (!priceMax_DSSP.getText().isEmpty() && !priceMin_DSSP.getText().isEmpty()) {
            if(priceMin_DSSP.getText().matches("-?\\d+") && priceMax_DSSP.getText().matches("-?\\d+") ) {
                min = Integer.parseInt(priceMin_DSSP.getText());
                max = Integer.parseInt(priceMax_DSSP.getText());
                if(min < 0 || max <= 0) {
                    JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ", "Invalid", JOptionPane.OK_CANCEL_OPTION);
                } else if (max <= min) {
                    JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ", "Invalid", JOptionPane.OK_CANCEL_OPTION);
                }
                else { // Truong hop nguoi dung nhap menh gia tien
                        data = new Vector();
                        DefaultTableModel model;
                        model = (DefaultTableModel) this.tbListSach.getModel();
                        ArrayList<Sach> lstBookById = SachDAO.getBookByPrice(min, max);
                        if (!lstBookById.isEmpty()) {
                             for (Sach sach : lstBookById) {
                                Vector<Object> vec = new Vector<>();
                                vec.add(sach.getMasach());
                                vec.add(sach.getTensach());
                                vec.add(sach.getGiaban());
                                vec.add(sach.getMota());
                                vec.add(sach.getNgaycapnhat());
                                vec.add(sach.getMaanhbia());
                                vec.add(sach.getSoluongton());
                                vec.add(sach.getMachude());
                                vec.add(sach.getManxb());
                                vec.add(sach.getMoi());
                                data.add(vec);

                            }

                        }
                        model.setDataVector(data, header);
                }
            }else {
                 JOptionPane.showMessageDialog(this, "Giá tiền phải là số", "Error", JOptionPane.OK_CANCEL_OPTION);
            }
        }

    }
     
    private void actionSearchTypes() {
        String typesBook = String.valueOf(cbbMaChuDe_Search.getSelectedItem());
        if(typesBook != "Khong") {
            data = new Vector();
            DefaultTableModel model;
            model = (DefaultTableModel) this.tbListSach.getModel();
            ArrayList<Sach> lstBookById = SachDAO.getBookByTypes(typesBook);
            if (!lstBookById.isEmpty()) {
                 for (Sach sach : lstBookById) {
                    Vector<Object> vec = new Vector<>();

                    vec.add(sach.getMasach());
                    vec.add(sach.getTensach());
                    vec.add(sach.getGiaban());
                    vec.add(sach.getMota());
                    vec.add(sach.getNgaycapnhat());
                    vec.add(sach.getMaanhbia());
                    vec.add(sach.getSoluongton());
                    vec.add(sach.getMachude());
                    vec.add(sach.getManxb());
                    vec.add(sach.getMoi());
                    data.add(vec);
                }
            }
            model.setDataVector(data, header); 
        }
    }

    private void actionSearchMaSach() {
        if(txtMaSach_Search_DSSP.getText().matches("\\d+")) {
            data = new Vector();
            DefaultTableModel model;
            model = (DefaultTableModel) this.tbListSach.getModel();
//            System.out.println(txtMaSach_Search_DSSP);
            ArrayList<Sach> lstBookById = SachDAO.getBookById( Integer.parseInt(txtMaSach_Search_DSSP.getText()));
            if (!lstBookById.isEmpty()) {
                 for (Sach sach : lstBookById) {
                    Vector<Object> vec = new Vector<>();

                    vec.add(sach.getMasach());
                    vec.add(sach.getTensach());
                    vec.add(sach.getGiaban());
                    vec.add(sach.getMota());
                    vec.add(sach.getNgaycapnhat());
                    vec.add(sach.getMaanhbia());
                    vec.add(sach.getSoluongton());
                    vec.add(sach.getMachude());
                    vec.add(sach.getManxb());
                    vec.add(sach.getMoi());
                    data.add(vec);
                }
            }
            model.setDataVector(data, header);
        }
        else if (txtMaSach_Search_DSSP.getText().isEmpty()) {
        }
        else {
            JOptionPane.showMessageDialog(this, "Ma Sach Khong Hop Le", "Invalid", JOptionPane.OK_CANCEL_OPTION);
        }     
    }
    
    private void tbListSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListSachMouseClicked
        // TODO add your handling code here:
        int row = this.tbListSach.getSelectedRow();
        this.txtMaSach.setText( String.valueOf(this.tbListSach.getValueAt(row, 0)));
        this.txtMaSach.setEditable(false);
        this.txtTenSach.setText(String.valueOf(this.tbListSach.getValueAt(row, 1)));
        this.txtDonGia.setText(String.valueOf(this.tbListSach.getValueAt(row, 2)));
        this.txtSoLuong.setText(String.valueOf(this.tbListSach.getValueAt(row, 6)));
        this.txtMaNXB.setText(String.valueOf(this.tbListSach.getValueAt(row, 8)));
        for (Object type : SachDAO.getBookTypes()) {
            String typeName = String.valueOf(type);
            // Loại bỏ dấu [ và ] nếu có
            typeName = typeName.replace("[", "").replace("]", "");
            String cellValue = String.valueOf(this.tbListSach.getValueAt(row, 7));
            if (typeName.equals(cellValue)) {
                cbbMaChuDe.setSelectedItem(typeName);
            }
        }
    }//GEN-LAST:event_tbListSachMouseClicked

    private void tbListSachMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListSachMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbListSachMouseReleased

    private void cbbMaChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaChuDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMaChuDeActionPerformed

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        this.txtMaSach.setText("");
        this.txtMaSach_Search_DSSP.setText("");
        this.txtMaSach_Search_DSSP.setEditable(true);
        this.txtTenSach_Search_DSSP.setText("");
        this.txtTenSach_Search_DSSP.setEditable(true);
        this.txtTenSach.setText("");
        this.txtDonGia.setText("");
        this.txtDonGia.setEditable(true);
        this.txtSoLuong.setText("");
        this.txtSoLuong.setEditable(true);
        this.txtMaNXB.setText("");
        this.txtMaNXB.setEditable(true);
        this.cbbMaChuDe.setSelectedIndex(0);
        this.cbbMaChuDe.setEnabled(true);

        this.cbbMaNXB_Search.setSelectedIndex(0);
        DefaultTableModel tMOdel = (DefaultTableModel) tbListSach.getModel();
        tMOdel.setRowCount(0);
        tMOdel.setColumnCount(0);
        this.cbbMaChuDe_Search.setSelectedIndex(0);
        
        this.priceMax_DSSP.setText("");
        this.priceMin_DSSP.setText("");
        
        loadDanhSachSach();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtMaSach_Search_DSSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSach_Search_DSSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSach_Search_DSSPActionPerformed

    private void bntXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXacNhanActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        fromTTHoaDon.Instance.toFront();
        fromTTHoaDon.Instance.setState(java.awt.Frame.NORMAL);
//        
//        formHoaDon.txtMaSach.setText(this.txtMaSach.getText());
        fromTTHoaDon.Instance.txtMaSach.setText(this.txtMaSach.getText());
        fromTTHoaDon.Instance.txtTenSach.setText(this.txtTenSach.getText());
        fromTTHoaDon.Instance.txtDonGia.setText(this.txtDonGia.getText());
    }//GEN-LAST:event_bntXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Middle;
    private javax.swing.JButton bntTimKiem;
    private javax.swing.JButton bntXacNhan;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JComboBox<String> cbbMaChuDe;
    private javax.swing.JComboBox<String> cbbMaChuDe_Search;
    private javax.swing.JComboBox<String> cbbMaNXB;
    private javax.swing.JComboBox<String> cbbMaNXB_Search;
    private javax.swing.JComboBox<String> cbbMaTheLoai;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceMax;
    private javax.swing.JTextField priceMax_DSSP;
    private javax.swing.JTextField priceMin;
    private javax.swing.JTextField priceMin_DSSP;
    private javax.swing.JTable tbListSach;
    private javax.swing.JLabel titlePage;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaNXB;
    public javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMaSach_Search;
    private javax.swing.JTextField txtMaSach_Search_DSSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia_Search;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenSach_Search;
    private javax.swing.JTextField txtTenSach_Search_DSSP;
    // End of variables declaration//GEN-END:variables
}
