/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.SQLServerDataProvider;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Base64;
import javax.swing.JOptionPane;
/**
 *
 * @author Ther
 */
public class formTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form formTaiKhoan
     */
    Vector data = new Vector();
    Vector<String> header = new Vector();
    DefaultTableModel model;
    public formTaiKhoan() {
        initComponents();
        loadData();
        
        this.bntBinhThuong.setActionCommand("Bình thường");
        this.bntKhoa.setActionCommand("Khóa");
    }
    
    private void loadData() {
        header.add("Mã TK");
        header.add("Tên Tài Khoản");
        header.add("Mật Khẩu");
        header.add("Quyền");
        header.add("Trạng Thái");
        
        
        DefaultTableModel model;
        model = (DefaultTableModel) this.tbTaiKhoan.getModel();
        
        Vector admin = new Vector();
        String MaTK = "A01";
        String TenTK = FromLogin.Instance.txt_user.getText();
        String MK = FromLogin.Instance.txt_password.getText();

        String Quyen = String.valueOf(cbbQuyen.getItemAt(0));
        String TrangThai = "Bình thường";
        
        if (TenTK.equals("admin") || TenTK.equals("Admin") || TenTK.equals("sa")) {
            Quyen = "Admin";
        }else 
            Quyen = "BT";
     
        admin.add(MaTK);
        admin.add(TenTK);
        admin.add(MK);
        admin.add(Quyen);
        admin.add(TrangThai);
        
        data.add(admin);
        
        model.setDataVector(data, header);
    }
    
    private boolean checkValid(String MaNV, String TenDangNhap) {
        String existsTK = "";
        String existsMaNV = "";
        
        boolean flagTK = false;
        boolean flagMaNV = false;
        
        for (int i = 0; i < tbTaiKhoan.getRowCount(); i++) {
            existsTK = String.valueOf(tbTaiKhoan.getValueAt(i, 1));
            existsMaNV = String.valueOf(tbTaiKhoan.getValueAt(i, 0));
            if (existsTK.equals(this.txtTenDangNhap.getText()) || existsMaNV.equals(this.txtMaNhanVien.getText())) {
                flagTK = true;
                flagMaNV = true;
            }
        }
        
        return flagMaNV && flagTK;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseGrant = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        titlePage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bntThemTK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntXoaTK = new javax.swing.JButton();
        bntSuaTK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();
        cbbQuyen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bntBinhThuong = new javax.swing.JRadioButton();
        bntKhoa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setForeground(new java.awt.Color(0, 255, 255));

        titlePage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePage.setForeground(new java.awt.Color(255, 255, 255));
        titlePage.setText("QUẢN LÝ TÀI KHOẢN");

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlePage)
                .addGap(248, 248, 248)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePage)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bntThemTK.setBackground(new java.awt.Color(0, 153, 204));
        bntThemTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntThemTK.setText("Thêm");
        bntThemTK.setPreferredSize(new java.awt.Dimension(72, 36));
        bntThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThemTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Nhân Viên ");

        bntXoaTK.setBackground(new java.awt.Color(255, 0, 0));
        bntXoaTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntXoaTK.setText("Xóa");
        bntXoaTK.setPreferredSize(new java.awt.Dimension(72, 36));
        bntXoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaTKActionPerformed(evt);
            }
        });

        bntSuaTK.setBackground(new java.awt.Color(0, 153, 51));
        bntSuaTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntSuaTK.setText("Sửa");
        bntSuaTK.setMaximumSize(new java.awt.Dimension(72, 36));
        bntSuaTK.setPreferredSize(new java.awt.Dimension(72, 36));
        bntSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSuaTKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Đăng Nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mật Khẩu");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quyền");

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTaiKhoan);

        cbbQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "BT" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Trạng thái");

        chooseGrant.add(bntBinhThuong);
        bntBinhThuong.setText("Bình thường");

        chooseGrant.add(bntKhoa);
        bntKhoa.setText("Khóa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bntThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenDangNhap)
                                    .addComponent(txtMaNhanVien)
                                    .addComponent(txtMatKhau)
                                    .addComponent(cbbQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bntXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bntSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntBinhThuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntKhoa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntBinhThuong)
                            .addComponent(bntKhoa)
                            .addComponent(jLabel5))
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bntThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThemTKActionPerformed
        // TODO add your handling code here:
        
        
        
        if(!checkValid(this.txtMaNhanVien.getText(), this.txtTenDangNhap.getText())) {
            Vector newTaiKhoan = new Vector();
            
            String MaTK = this.txtMaNhanVien.getText();
            String Quyen = String.valueOf(cbbQuyen.getSelectedItem());
            String TrangThai = chooseGrant.getSelection().getActionCommand();
            
            newTaiKhoan.add(MaTK);
            newTaiKhoan.add(this.txtTenDangNhap.getText());
            newTaiKhoan.add(this.txtMatKhau.getText());
            newTaiKhoan.add(Quyen);
            newTaiKhoan.add(TrangThai);

            data.add(newTaiKhoan);
            
            model = (DefaultTableModel)this.tbTaiKhoan.getModel();
            model.setDataVector(data, header);
            this.tbTaiKhoan.updateUI();
            
        } else {
            JOptionPane.showConfirmDialog(this, "Tài khoản đã tồn tại", "Error", JOptionPane.OK_CANCEL_OPTION);
        }
        
    }//GEN-LAST:event_bntThemTKActionPerformed

    private void bntXoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaTKActionPerformed
        // TODO add your handling code here:
        int row = this.tbTaiKhoan.getSelectedRow();
        boolean TenTK = String.valueOf(this.tbTaiKhoan.getValueAt(row, 1)).equals(FromLogin.Instance.txt_user.getText());
        if(TenTK) {
            JOptionPane.showConfirmDialog(this, "Tài khoản hiện tại đang đăng nhập", "Error", JOptionPane.OK_CANCEL_OPTION);
        } else {
            model.removeRow(row);
            this.tbTaiKhoan.updateUI();
        }
    }//GEN-LAST:event_bntXoaTKActionPerformed

    private void bntSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSuaTKActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_bntSuaTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bntBinhThuong;
    private javax.swing.JRadioButton bntKhoa;
    private javax.swing.JButton bntSuaTK;
    private javax.swing.JButton bntThemTK;
    private javax.swing.JButton bntXoaTK;
    private javax.swing.JComboBox<String> cbbQuyen;
    private javax.swing.ButtonGroup chooseGrant;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JLabel titlePage;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
