/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import dao.KhachHangDAO;
import dao.SQLServerDataProvider;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.KhachHang;
import javax.swing.*;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author TUAN KIET
 */
public class formQuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form formQuanLyKhachHang
     */
    public String taiKhoan;
    public String matKhau;
    DefaultTableModel dtm = new DefaultTableModel();
    public formQuanLyKhachHang() {
        initComponents();
        this.setTitle("Quản lý khách hàng");
        this.setLocationRelativeTo(null);
        String [] tieuDe = {"Mã Khách Hàng", "Tên Khách Hàng","Ngày Sinh", "Giới Tính","Điện Thoại", "Tài Khoản", "Mật Khẩu", "Email","Địa Chỉ"};
        dtm.setColumnIdentifiers(tieuDe);
        tbDanhSach.setModel(dtm);
        
        txtMaKH.disable();
        
        ArrayList<KhachHang> dsKH = KhachHangDAO.layDanhSachKhachHang();
        DefaultTableModel dtmKhachHang = (DefaultTableModel)tbDanhSach.getModel();
        dtmKhachHang.setRowCount(0);
        for(KhachHang pb:dsKH){
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaKH());
            v.add(pb.getTenKH());
            v.add(pb.getNgaySinh());
            v.add(pb.getGioiTinh());
            v.add(pb.getDienThoai());
            v.add(pb.getTaiKhoan());
            v.add(pb.getMatKhau());
            v.add(pb.getEmail());
            v.add(pb.getDiaChi());
            dtmKhachHang.addRow(v);
            
        }
        tbDanhSach.setModel(dtmKhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTaiKhoan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbTimKiem = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_NgaySinh = new com.toedter.calendar.JDateChooser();
        cbGioiTinh = new javax.swing.JComboBox<>();
        ck_passs = new javax.swing.JCheckBox();
        txtMatKhau = new javax.swing.JPasswordField();
        btnXuat = new javax.swing.JButton();

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Nhập Excel");

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Xuất Excel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16))
        );

        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDanhSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Nhập Thông Tin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã KH:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Địa Chỉ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("SĐT:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Giới Tính:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Ngày Sinh");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tài Khoản:");

        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 153, 51));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 0, 0));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 0, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(255, 153, 0));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        cbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên Khách Hàng", "Mã Khách Hàng", "Địa Chỉ", "Tài Khoản" }));

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 51));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTimKiem)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mật Khẩu:");

        txt_NgaySinh.setDateFormatString("yyyy-MM-dd");

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        ck_passs.setText("Hiển Thị Mật Khẩu");
        ck_passs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_passsActionPerformed(evt);
            }
        });

        btnXuat.setBackground(new java.awt.Color(204, 0, 255));
        btnXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnXuat.setText("Xuất Excel");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(63, 63, 63))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ck_passs)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnLamMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXuat)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ck_passs))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnXoa)
                                    .addComponent(btnSua)
                                    .addComponent(btnLamMoi)
                                    .addComponent(btnThem)
                                    .addComponent(btnXuat)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachMouseClicked
        // TODO add your handling code here:
        int row = tbDanhSach.getSelectedRow();
        txtMaKH.setText((String.valueOf(Integer.parseInt(tbDanhSach.getValueAt(row, 0).toString()))));
        txtHoTen.setText((String)tbDanhSach.getValueAt(row, 1));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = txt_NgaySinh.getDate();
        String ngaySinh = "";
        if (date != null) {
            ngaySinh = sdf.format(date);
        }
        //txt_NgaySinh.setDate((Date)tbDanhSach.getValueAt(row, 2));
        

        cbGioiTinh.setSelectedItem((String)tbDanhSach.getValueAt(row, 3));
        txtSDT.setText((String)tbDanhSach.getValueAt(row, 4));
        txtTaiKhoan.setText((String)tbDanhSach.getValueAt(row, 5));
        String matKhau = (String)tbDanhSach.getValueAt(row, 6);
        if (matKhau != null) {
            txtMatKhau.setText(matKhau.replaceAll(".", "*"));
        } else {
            txtMatKhau.setText("");
        }
        txtEmail.setText((String)tbDanhSach.getValueAt(row, 7));
        txtDiaChi.setText((String)tbDanhSach.getValueAt(row, 8));
    }//GEN-LAST:event_tbDanhSachMouseClicked

    private void ck_passsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_passsActionPerformed
        // TODO add your handling code here:;
        taiKhoan = txtTaiKhoan.getText();
        matKhau = new String(txtMatKhau.getPassword());
        if (ck_passs.isSelected()) {
            matKhau = txtMatKhau.getText();
        }
        if (ck_passs.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_ck_passsActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(cbTimKiem.getSelectedItem()=="Tên Khách Hàng"){
            ArrayList<KhachHang> dsKH = KhachHangDAO.timKiemKhachHangTheoTen(txtTimKiem.getText());
            DefaultTableModel dtmKhachHang = (DefaultTableModel)tbDanhSach.getModel();
            dtmKhachHang.setRowCount(0);
            for(KhachHang kh:dsKH){
                Vector<Object> v = new Vector<Object>();
                v.add(kh.getMaKH());
                v.add(kh.getTenKH());
                v.add(kh.getNgaySinh());
                v.add(kh.getGioiTinh());
                v.add(kh.getDienThoai());
                v.add(kh.getTaiKhoan());
                v.add(kh.getMatKhau());
                v.add(kh.getEmail());
                v.add(kh.getDiaChi());
                dtmKhachHang.addRow(v);

            }
            tbDanhSach.setModel(dtmKhachHang);
        }else if(cbTimKiem.getSelectedItem()=="Mã Khách Hàng"){
            ArrayList<KhachHang> dsKH = KhachHangDAO.timKiemKhachHangTheoMa(txtTimKiem.getText());
            DefaultTableModel dtmKhachHang = (DefaultTableModel)tbDanhSach.getModel();
            dtmKhachHang.setRowCount(0);
            for(KhachHang kh:dsKH){
                Vector<Object> v = new Vector<Object>();
                v.add(kh.getMaKH());
                v.add(kh.getTenKH());
                v.add(kh.getNgaySinh());
                v.add(kh.getGioiTinh());
                v.add(kh.getDienThoai());
                v.add(kh.getTaiKhoan());
                v.add(kh.getMatKhau());
                v.add(kh.getEmail());
                v.add(kh.getDiaChi());
                dtmKhachHang.addRow(v);

            }
            tbDanhSach.setModel(dtmKhachHang);
        }else if(cbTimKiem.getSelectedItem()=="Địa Chỉ"){
            ArrayList<KhachHang> dsKH = KhachHangDAO.timKiemKhachHangDiaChi(txtTimKiem.getText());
            DefaultTableModel dtmKhachHang = (DefaultTableModel)tbDanhSach.getModel();
            dtmKhachHang.setRowCount(0);
            for(KhachHang kh:dsKH){
                Vector<Object> v = new Vector<Object>();
                v.add(kh.getMaKH());
                v.add(kh.getTenKH());
                v.add(kh.getNgaySinh());
                v.add(kh.getGioiTinh());
                v.add(kh.getDienThoai());
                v.add(kh.getTaiKhoan());
                v.add(kh.getMatKhau());
                v.add(kh.getEmail());
                v.add(kh.getDiaChi());
                dtmKhachHang.addRow(v);

            }
            tbDanhSach.setModel(dtmKhachHang);
        }else if(cbTimKiem.getSelectedItem()=="Tài Khoản"){
            ArrayList<KhachHang> dsKH = KhachHangDAO.timKiemKhachHangTheoTaiKhoan(txtTimKiem.getText());
            DefaultTableModel dtmKhachHang = (DefaultTableModel)tbDanhSach.getModel();
            dtmKhachHang.setRowCount(0);
            for(KhachHang kh:dsKH){
                Vector<Object> v = new Vector<Object>();
                v.add(kh.getMaKH());
                v.add(kh.getTenKH());
                v.add(kh.getNgaySinh());
                v.add(kh.getGioiTinh());
                v.add(kh.getDienThoai());
                v.add(kh.getTaiKhoan());
                v.add(kh.getMatKhau());
                v.add(kh.getEmail());
                v.add(kh.getDiaChi());
                dtmKhachHang.addRow(v);

            }
            tbDanhSach.setModel(dtmKhachHang);
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int maKH = Integer.parseInt(txtMaKH.getText());
                String tenKH = txtHoTen.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String ngaySinh = sdf.format(txt_NgaySinh.getDate());
                String gioiTinh = cbGioiTinh.getSelectedItem().toString();
                String dienThoai = txtSDT.getText();
                String taiKhoan = txtTaiKhoan.getText();
                String matKhau = txtMatKhau.getText();
                String email = txtEmail.getText();
                String diaChi = txtDiaChi.getText();
                KhachHang kh = new KhachHang();
                kh.setMaKH(maKH);
                kh.setTenKH(tenKH);
                kh.setNgaySinh(ngaySinh);
                kh.setGioiTinh(gioiTinh);
                kh.setDienThoai(dienThoai);
                kh.setTaiKhoan(taiKhoan);
                kh.setMatKhau(matKhau);
                kh.setEmail(email);
                kh.setDiaChi(diaChi);
                KhachHangDAO.capNhatKhachHang(kh);
                DefaultTableModel model = (DefaultTableModel) tbDanhSach.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (Integer.parseInt(model.getValueAt(i, 0).toString()) == maKH) {
                        model.setValueAt(tenKH, i, 1); 
                        model.setValueAt(ngaySinh, i, 2); 
                        model.setValueAt(gioiTinh, i, 3); 
                        model.setValueAt(dienThoai, i, 4); 
                        model.setValueAt(taiKhoan, i, 5); 
                        model.setValueAt(matKhau, i, 6); 
                        model.setValueAt(email, i, 7); 
                        model.setValueAt(diaChi, i, 8); 
                        break;
                    }
                }
                JOptionPane.showMessageDialog(this, "Cập Nhật Khách Hàng Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int maKH = Integer.parseInt(txtMaKH.getText());
        KhachHang kh = new KhachHang();
        kh.setMaKH(maKH);
        KhachHangDAO.xoaKhachHang(kh);
        DefaultTableModel model = (DefaultTableModel) tbDanhSach.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (Integer.parseInt(model.getValueAt(i, 0).toString()) == maKH) {
                model.removeRow(i);
                break;
            }
        }
        JOptionPane.showMessageDialog(this, "Xóa Khách Hàng Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String tenKH = txtHoTen.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinhString = sdf.format(txt_NgaySinh.getDate());
        String gioiTinh = cbGioiTinh.getSelectedItem().toString();
        String dienThoai = txtSDT.getText();
        String taiKhoan = txtTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        String email = txtEmail.getText();
        String diaChi = txtDiaChi.getText();
        KhachHang kh = new KhachHang();
        kh.setTenKH(tenKH);
        kh.setNgaySinh(ngaySinhString);
        kh.setGioiTinh(gioiTinh);
        kh.setDienThoai(dienThoai);
        kh.setTaiKhoan(taiKhoan);
        kh.setMatKhau(matKhau);
        kh.setEmail(email);
        kh.setDiaChi(diaChi);
        KhachHangDAO.themKhachHang(kh);
        DefaultTableModel model = (DefaultTableModel) tbDanhSach.getModel();
        model.addRow(new Object[] {
            kh.getMaKH(),
            kh.getTenKH(),
            kh.getNgaySinh(),
            kh.getGioiTinh(),
            kh.getDienThoai(),
            kh.getTaiKhoan(),
            kh.getMatKhau(),
            kh.getEmail(),
            kh.getDiaChi()
        });
        JOptionPane.showMessageDialog(this, "Thêm Khách Hàng Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaKH.setText("");
        txtHoTen.setText("");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = txt_NgaySinh.getDate();
        String ngaySinh = "";
        if (date != null) {
            ngaySinh = sdf.format(date);
        }
        cbGioiTinh.setSelectedItem("Nam");
        txtSDT.setText("");
        txtTaiKhoan.setText("");
        txtMatKhau.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        ArrayList<KhachHang> arr = new ArrayList<KhachHang>();
        arr.clear();
         try
        {
            String sql = "Select * from khachhang";
            SQLServerDataProvider provider = new SQLServerDataProvider();
            provider.Open();
            ResultSet rs = provider.executeQuery(sql);
            while(rs.next()){
                KhachHang kh = new KhachHang();
                kh.setMaKH(rs.getInt("MaKH"));
                kh.setTenKH(rs.getString("HoTen"));
                kh.setNgaySinh(rs.getString("NgaySinh"));
                kh.setGioiTinh(rs.getString("GioiTinh"));
                kh.setDienThoai(rs.getString("DienThoai"));
                kh.setTaiKhoan(rs.getString("TaiKhoan"));
                kh.setMatKhau(rs.getString("MatKhau"));
                kh.setEmail(rs.getString("Email"));
                kh.setDiaChi(rs.getString("DiaChi"));
                arr.add(kh);
            }
            provider.Close();
        }
         
         
        catch(Exception e)
        {
            e.printStackTrace();
        }

        try
        {
        XSSFWorkbook wordkbook = new XSSFWorkbook();
        XSSFSheet sheet=wordkbook.createSheet("danhsach");
        XSSFRow row =null;
        Cell cell=null;
        row=sheet.createRow(2);
        cell=row.createCell(0,CellType.STRING);
        cell.setCellValue("DANH SÁCH KHÁCH HÀNG");
        
        row=sheet.createRow(3);
        cell=row.createCell(0,CellType.STRING);
        cell.setCellValue("STT");
        
        cell=row.createCell(1,CellType.STRING);
        cell.setCellValue("Mã Khách Hàng");
        
        cell=row.createCell(2,CellType.STRING);
        cell.setCellValue("Tên Khách Hàng");
        
        cell=row.createCell(3,CellType.STRING);
        cell.setCellValue("Ngày Sinh");
        
        cell=row.createCell(4,CellType.STRING);
        cell.setCellValue("Giới Tính");
        
        cell=row.createCell(5,CellType.STRING);
        cell.setCellValue("Điện Thoại");
        
        cell=row.createCell(6,CellType.STRING);
        cell.setCellValue("Tài Khoản");
        
        cell=row.createCell(7,CellType.STRING);
        cell.setCellValue("Mật Khẩu");
        
        cell=row.createCell(8,CellType.STRING);
        cell.setCellValue("Email");
        
        cell=row.createCell(9,CellType.STRING);
        cell.setCellValue("Địa Chỉ");
        
        for(int i=0; i<arr.size(); i++)
        {
            //Modelbook book =arr.get(i);
            row=sheet.createRow(4+i);
           
            cell=row.createCell(0,CellType.NUMERIC);
            cell.setCellValue(i+1);
            
            cell=row.createCell(1,CellType.STRING);
            cell.setCellValue(arr.get(i).getMaKH());
            
            
            cell=row.createCell(2,CellType.STRING);
            cell.setCellValue(arr.get(i).getTenKH());
            
            cell=row.createCell(3,CellType.STRING);
            cell.setCellValue(arr.get(i).getNgaySinh());
            
            cell=row.createCell(4,CellType.STRING);
            cell.setCellValue(arr.get(i).getGioiTinh());
            
            cell=row.createCell(5,CellType.STRING);
            cell.setCellValue(arr.get(i).getDienThoai());
            
            cell=row.createCell(6,CellType.STRING);
            cell.setCellValue(arr.get(i).getTaiKhoan());
            
            cell=row.createCell(7,CellType.STRING);
            cell.setCellValue(arr.get(i).getMatKhau());
            
            cell=row.createCell(8,CellType.STRING);
            cell.setCellValue(arr.get(i).getEmail());
            
            cell=row.createCell(9,CellType.STRING);
            cell.setCellValue(arr.get(i).getDiaChi());
                                  
        }
        
        File f = new File("D://danhsach.xlsx");
        try 
        {
            FileOutputStream fis = new FileOutputStream(f);
            wordkbook.write(fis);
            fis.close();
        }
        catch (FileNotFoundException ex) {
            ex.printStackTrace();
       
        }
        catch (IOException ex)
        {
          ex.printStackTrace();
        }
        
        
        JOptionPane.showMessageDialog(this, "in thanh cong D:\\danhsach");
        
        }
        
        
        catch(Exception ex)
        {
            ex.printStackTrace();
              JOptionPane.showMessageDialog(this, "Loi mo file");
        }

    }//GEN-LAST:event_btnXuatActionPerformed

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formQuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formQuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbTimKiem;
    private javax.swing.JCheckBox ck_passs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDanhSach;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    public javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    private com.toedter.calendar.JDateChooser txt_NgaySinh;
    // End of variables declaration//GEN-END:variables
}
