/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DonHangDAO;
import dao.TacGiaDAO;
import static gui.formDonHang.Instance;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.DonHang;
import pojo.TacGia;

/**
 *
 * @author nguye
 */
public class FormTacGia extends javax.swing.JFrame {
private String username;
private String password;
DefaultTableModel dtm = new DefaultTableModel();
    public FormTacGia(String username, String password) {
        this.username = username;
        this.password = password;
            this.setTitle("Tác Giả");
        this.setLocationRelativeTo(null);
        initComponents();
        setLocationRelativeTo(null);
        String[] tieude = {"Mã Tác Giả", "Tên Tác Giả", "Địa Chỉ", "SĐT", "Tiểu Sử"};
        dtm.setColumnIdentifiers(tieude);
        ArrayList<TacGia> dsTacGia = TacGiaDAO.hienThiDanhSachTacGia(username, password); // Truyền thông tin đăng nhập vào hàm
        dtm.setRowCount(0);
        for (TacGia tacGia : dsTacGia) {
            Vector<Object> vec = new Vector<>();
            vec.add(tacGia.getMaTacGia());
            vec.add(tacGia.getTenTacGia());
            vec.add(tacGia.getDiaChi());
            vec.add(tacGia.getDienThoai());
            vec.add(tacGia.getTieuSu());
            dtm.addRow(vec);
        }
        tb_TacGia.setModel(dtm);
    

    }

    /**
     * Creates new form FormTacGia
     */
    public FormTacGia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        titlePage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_MaTacGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenTacGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DIaChi = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_TieuSu = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BtnThem = new javax.swing.JButton();
        Btn_Update = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        BtnTim = new javax.swing.JButton();
        txt_Ten_Tac_Gia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_TacGia = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setForeground(new java.awt.Color(0, 255, 255));

        titlePage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePage.setForeground(new java.awt.Color(255, 255, 255));
        titlePage.setText("Tác Giả");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(titlePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePage)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã Tác Giả:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên Tác Giả:");

        txt_TenTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenTacGiaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tiểu Sử:");

        jScrollPane1.setViewportView(txt_DIaChi);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jScrollPane2.setViewportView(txt_TieuSu);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SĐT:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        BtnThem.setBackground(new java.awt.Color(153, 255, 153));
        BtnThem.setText("Thêm ");
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        Btn_Update.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Update.setText("Sữa ");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        BtnXoa.setBackground(new java.awt.Color(0, 204, 255));
        BtnXoa.setText("Xóa");
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        BtnTim.setBackground(new java.awt.Color(0, 153, 153));
        BtnTim.setText("Tìm");
        BtnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tên Tác Giả:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnThem)
                .addGap(18, 18, 18)
                .addComponent(Btn_Update)
                .addGap(18, 18, 18)
                .addComponent(BtnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Ten_Tac_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTim))
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem)
                    .addComponent(Btn_Update)
                    .addComponent(BtnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Ten_Tac_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTim)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(txt_TenTacGia))
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_MaTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_TenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tb_TacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_TacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TacGiaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb_TacGia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_TacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TacGiaMouseClicked
        // TODO add your handling code here:
         // Get the selected row index
    int selectedRow = tb_TacGia.getSelectedRow();
    
    // Get the data from the selected row
    String maTacGia = tb_TacGia.getValueAt(selectedRow, 0).toString();
    String tenTacGia = tb_TacGia.getValueAt(selectedRow, 1).toString();
    String diaChi = tb_TacGia.getValueAt(selectedRow, 2).toString();
    String tieuSu = tb_TacGia.getValueAt(selectedRow, 3).toString();
    String sdt = tb_TacGia.getValueAt(selectedRow, 4).toString();
    
    // Set the data to the corresponding text fields
    txt_MaTacGia.setText(maTacGia);
    txt_TenTacGia.setText(tenTacGia);
    txt_DIaChi.setText(diaChi);
    txt_SDT.setText(tieuSu);
    txt_TieuSu.setText(sdt);
    
    }//GEN-LAST:event_tb_TacGiaMouseClicked

    private void txt_TenTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenTacGiaActionPerformed

    private void BtnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimActionPerformed
        // TODO add your handling code here:
         String searchText = txt_Ten_Tac_Gia.getText().trim();
    
    // If the search text is empty, display all authors
    if (searchText.isEmpty()) {
        ArrayList<TacGia> dsTacGia = TacGiaDAO.hienThiDanhSachTacGia(username, password);
        dtm.setRowCount(0);
        for (TacGia tacGia : dsTacGia) {
            Vector<Object> vec = new Vector<>();
            vec.add(tacGia.getMaTacGia());
            vec.add(tacGia.getTenTacGia());
            vec.add(tacGia.getDiaChi());
            vec.add(tacGia.getDienThoai());
            vec.add(tacGia.getTieuSu());
            dtm.addRow(vec);
        }
    } else {
        // Filter the list based on the search text
        ArrayList<TacGia> dsTacGia = TacGiaDAO.hienThiDanhSachTacGia(username, password);
        dtm.setRowCount(0);
        for (TacGia tacGia : dsTacGia) {
            if (tacGia.getTenTacGia().toLowerCase().contains(searchText.toLowerCase())) {
                Vector<Object> vec = new Vector<>();
                vec.add(tacGia.getMaTacGia());
                vec.add(tacGia.getTenTacGia());
                vec.add(tacGia.getDiaChi());
                vec.add(tacGia.getDienThoai());
                vec.add(tacGia.getTieuSu());
                dtm.addRow(vec);
            }
        }
    }
    
    tb_TacGia.setModel(dtm);
    }//GEN-LAST:event_BtnTimActionPerformed

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
            // Collect data from text fields
    String tenTacGia = txt_TenTacGia.getText();
    String diaChi = txt_DIaChi.getText();
    String dienThoai = txt_SDT.getText();
    String tieuSu = txt_TieuSu.getText();
    
    // Check if all fields are filled
    if (tenTacGia.isEmpty() || diaChi.isEmpty() || dienThoai.isEmpty() || tieuSu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Create a new TacGia object
    TacGia tacGia = new TacGia();
    tacGia.setTenTacGia(tenTacGia);
    tacGia.setDiaChi(diaChi);
    tacGia.setDienThoai(dienThoai);
    tacGia.setTieuSu(tieuSu);
    
    // Call the themTacGia method to add the new author
    boolean isSuccess = TacGiaDAO.themTacGia(username, password, tacGia);
    
    if (isSuccess) {
        JOptionPane.showMessageDialog(this, "Thêm tác giả thành công!");
         loadTableData();
        clearInputFields(); // Clear the input fields
    } else {
        JOptionPane.showMessageDialog(this, "Thêm tác giả thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnThemActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        // TODO add your handling code here:
         // Lấy thông tin từ các trường nhập liệu
    int maTacGia = Integer.parseInt(txt_MaTacGia.getText()); // Lấy mã tác giả từ trường mã tác giả (txt_MaTacGia)
    String tenTacGia = txt_TenTacGia.getText(); // Lấy tên tác giả từ trường tên tác giả (txt_TenTacGia)
    String diaChi = txt_DIaChi.getText(); // Lấy địa chỉ từ trường địa chỉ (txt_DIaChi)
    String sdt = txt_SDT.getText(); // Lấy số điện thoại từ trường số điện thoại (txt_SDT)
    String tieuSu = txt_TieuSu.getText(); // Lấy tiểu sử từ trường tiểu sử (txt_TieuSu)
    
    // Kiểm tra nếu các trường nhập liệu không được điền đầy đủ
    if (tenTacGia.isEmpty() || diaChi.isEmpty() || sdt.isEmpty() || tieuSu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Tạo một đối tượng TacGia mới chứa thông tin cập nhật
    TacGia tacGiaToUpdate = new TacGia();
    tacGiaToUpdate.setMaTacGia(maTacGia);
    tacGiaToUpdate.setTenTacGia(tenTacGia);
    tacGiaToUpdate.setDiaChi(diaChi);
    tacGiaToUpdate.setDienThoai(sdt);
    tacGiaToUpdate.setTieuSu(tieuSu);
    
    // Gọi phương thức cập nhật tác giả từ lớp TacGiaDAO
    boolean isSuccess = TacGiaDAO.capNhatTacGia(username, password, tacGiaToUpdate);
    
    // Hiển thị thông báo tùy thuộc vào kết quả cập nhật
    if (isSuccess) {
        JOptionPane.showMessageDialog(this, "Cập nhật thông tin tác giả thành công!");
        // Gọi phương thức tải lại dữ liệu trên bảng
      loadTableData();
        // Xóa trắng các trường nhập liệu sau khi cập nhật thành công
        clearInputFields();
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật thông tin tác giả thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
    // Lấy mã tác giả từ hàng được chọn trong bảng (giả sử cột đầu tiên chứa mã tác giả)
    int selectedRowIndex = tb_TacGia.getSelectedRow();
    if (selectedRowIndex == -1) {
        // Không có hàng nào được chọn, hiển thị thông báo lỗi
        JOptionPane.showMessageDialog(this, "Vui lòng chọn tác giả để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Lấy giá trị của cột đầu tiên (chứa mã tác giả) từ hàng được chọn
    int maTacGia = (int) tb_TacGia.getValueAt(selectedRowIndex, 0);

    // Xác nhận trước khi xóa
    int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tác giả này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
    if (choice != JOptionPane.YES_OPTION) {
        return; // Nếu người dùng chọn "No" hoặc đóng hộp thoại, không thực hiện xóa
    }

    // Thực hiện xóa tác giả
    boolean isSuccess = TacGiaDAO.xoaTacGia(username, password, maTacGia);
    
    if (isSuccess) {
        // Nếu xóa thành công, hiển thị thông báo và cập nhật bảng
        JOptionPane.showMessageDialog(this, "Xóa tác giả thành công!");
        loadTableData(); // Gọi phương thức để cập nhật lại bảng danh sách tác giả
    } else {
        // Nếu xóa không thành công, hiển thị thông báo lỗi
        JOptionPane.showMessageDialog(this, "Xóa tác giả thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void clearInputFields() {
    txt_MaTacGia.setText("");
    txt_TenTacGia.setText("");
    txt_DIaChi.setText("");
    txt_SDT.setText("");
    txt_TieuSu.setText("");
}
    private void loadTableData() {
    ArrayList<TacGia> dsTacGia = TacGiaDAO.hienThiDanhSachTacGia(username, password);
    dtm.setRowCount(0);
    for (TacGia tacGia : dsTacGia) {
        Vector<Object> vec = new Vector<>();
        vec.add(tacGia.getMaTacGia());
        vec.add(tacGia.getTenTacGia());
        vec.add(tacGia.getDiaChi());
        vec.add(tacGia.getDienThoai());
        vec.add(tacGia.getTieuSu());
        dtm.addRow(vec);
    }
    tb_TacGia.setModel(dtm);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTacGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnTim;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tb_TacGia;
    private javax.swing.JLabel titlePage;
    private javax.swing.JTextPane txt_DIaChi;
    private javax.swing.JTextField txt_MaTacGia;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenTacGia;
    private javax.swing.JTextField txt_Ten_Tac_Gia;
    private javax.swing.JTextPane txt_TieuSu;
    // End of variables declaration//GEN-END:variables
}
